// angular-10-demo/projects/hello-world/src/app/button/button.component.ts
import { Component, OnInit, Input } from '@angular/core';

export class ButtonDisplay {
  static readonly PRIMARY = 'primary';
  static readonly SECONDARY = 'secondary';
}

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss']
})
export class ButtonComponent implements OnInit {
  @Input() display: string;

  constructor() { }

  ngOnInit(): void {
    this.display = this.display || ButtonDisplay.PRIMARY; // Default to primary
  }

}

<button [ngClass]="{
		'btn':true,
		'btn-primary':display === 'primary',
		'btn-secondary':display === 'secondary'
	}">
	<ng-content></ng-content>
</button>

// react-demo/src/components/button/Button.jsx
import React from "react";

import "./Button.scss";

export const buttonDisplay = {
	PRIMARY: "primary",
	SECONDARY: "secondary"
};

class Button extends React.Component {
	constructor(props){
		super(props);
	}

	render(){
		const {children, display, ...remaining} = this.props;
		const disp = display || buttonDisplay.PRIMARY; //Default

		return (
			<button className={`btn btn-${disp}`} {...remaining}>{children}</button>
		);
	}
}
export default Button;
